package source



/**
 * Ermis API client.
 *
 * The methods of the class execute <Requests>, generated by the
 * DSL methods. We map API calls to a <Future> objects.
 * An implicit <ExecutionContext> must be in scope.
 *
 */
trait Client {

}
